"""Added Cleaner model

Revision ID: 4c8185da183e
Revises: 8b036670411d
Create Date: 2023-12-12 12:39:52.930812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c8185da183e'
down_revision: Union[str, None] = '8b036670411d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cleaners',
    sa.Column('cleaner_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=25), nullable=True),
    sa.Column('contact_number', sa.Integer(), nullable=True),
    sa.Column('experience_level', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('cleaner_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cleaners')
    # ### end Alembic commands ###
